import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalAlarm from "../components/AlarmMonitor"; // <--- 1. TAMBAHKAN IMPORT INI

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TaskFlow", // Saya ubah judulnya jadi TaskFlow biar rapi
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 2. PASANG ALARM DISINI (Sebelum children) */}
        <GlobalAlarm />
        
        {children}
      </body>
    </html>
  );
}